<?php

namespace Database\Seeders;

use App\Models\Properties;
use Carbon\Carbon;
use DB;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class PropertiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run()
    {
        $properties = [
            [
                'id' => 1,
                'project_id' => 1,
                'property_name' => 'THE HIGHCLERE',
                'property_id' => '786',
                'price' => 1000.00,
                'before_price_label' => 'AED',
                'after_price_label' => 'Per Month',
                'price_unit' => 'Thousand',
                'price_on_call' => 'no',
                'size' => '123',
                'land' => '1232',
                'room' => 5,
                'bedroom' => 2,
                'bathroom' => 2,
                'garages' => 3,
                'garages_size' => '123',
                'year_built' => '2333',
                'city_id' => 2,
                'state_id' => 5,
                'country_id' => 5,
                'description' => '4 Bedroom Townhouse',
                'address' => 'Meydan, District 11',
                'google_map' => 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d7224.329489895229!2d55.349745928515816!3d25.130120541815838!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f65ea424d2979%3A0x89827b3c2b1db1a6!2sKnightsbridge%20Meydan!5e0!3m2!1sen!2sbd!4v1747580277141!5m2!1sen!2sbd',
                'video_url' => 'luDqXPm8z5k',
                'featured_image' => 'assets/images/properties/lYx0PrFjmbnosuB5REYbeX0TGUa6y6UXu8LMDwDz.webp',
                'file_attachment' => null,
                'status' => 'active',
                'for_rent' => true,
                'for_sale' => true,
                'hot_offer' => true,
                'sale' => true,
                'sold' => true,
                'created_at' => Carbon::parse('2025-06-05 08:23:27'),
                'updated_at' => Carbon::parse('2025-06-14 11:58:37'),
            ],
            [
                'id' => 2,
                'project_id' => 1,
                'property_name' => 'THE GROSVENOR',
                'property_id' => null,
                'price' => null,
                'before_price_label' => null,
                'after_price_label' => null,
                'price_unit' => null,
                'price_on_call' => 'no',
                'size' => null,
                'land' => null,
                'room' => null,
                'bedroom' => null,
                'bathroom' => null,
                'garages' => null,
                'garages_size' => null,
                'year_built' => null,
                'city_id' => null,
                'state_id' => null,
                'country_id' => null,
                'description' => null,
                'address' => 'Meydan, District 11',
                'google_map' => '<iframe src="https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d14448.64934409665!2d55.351846!3d25.130202!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5f65ea424d2979%3A0x89827b3c2b1db1a6!2sKnightsbridge%20Meydan!5e0!3m2!1sen!2sbd!4v1749135786186!5m2!1sen!2sbd" width="100%" height="450" style="border:0;" allowfullscreen="" loading="lazy" referrerpolicy="no-referrer-when-downgrade"></iframe>',
                'video_url' => 'https://www.youtube.com/watch?v=qlhKvQ_oM4k',
                'featured_image' => 'assets/images/properties/yfj98aIEjkL95UQgs6gCGM0YRDJf2dJxBHdzI9B3.webp',
                'file_attachment' => null,
                'status' => 'active',
                'for_rent' => true,
                'for_sale' => true,
                'hot_offer' => null,
                'sale' => null,
                'sold' => null,
                'created_at' => Carbon::parse('2025-06-05 08:28:50'),
                'updated_at' => Carbon::parse('2025-06-14 11:59:31'),
            ],
            [
                'id' => 3,
                'project_id' => 1,
                'property_name' => 'THE BALMORAL',
                'property_id' => '12341',
                'price' => 1000.00,
                'before_price_label' => 'AED',
                'after_price_label' => 'Per Month',
                'price_unit' => 'Thousand',
                'price_on_call' => 'no',
                'size' => '123',
                'land' => '123123',
                'room' => 5,
                'bedroom' => 2,
                'bathroom' => 5,
                'garages' => 3,
                'garages_size' => '123',
                'year_built' => '2333',
                'city_id' => 2,
                'state_id' => 5,
                'country_id' => 3,
                'description' => 'fsdf',
                'address' => null,
                'google_map' => null,
                'video_url' => null,
                'featured_image' => 'assets/images/properties/uU1eLHNHCYJ3VKRQjcU6FF4Rntpwvy6FpbbbwF2S.webp',
                'file_attachment' => null,
                'status' => 'active',
                'for_rent' => false,
                'for_sale' => false,
                'hot_offer' => false,
                'sale' => false,
                'sold' => false,
                'created_at' => Carbon::parse('2025-06-05 08:29:26'),
                'updated_at' => Carbon::parse('2025-06-12 23:54:38'),
            ],
            [
                'id' => 4,
                'project_id' => 1,
                'property_name' => 'THE CHATSWORTH',
                'property_id' => null,
                'price' => 13.80,
                'before_price_label' => 'AED',
                'after_price_label' => null,
                'price_unit' => 'Million',
                'price_on_call' => 'yes',
                'size' => null,
                'land' => null,
                'room' => null,
                'bedroom' => 5,
                'bathroom' => null,
                'garages' => null,
                'garages_size' => null,
                'year_built' => null,
                'city_id' => 2,
                'state_id' => null,
                'country_id' => null,
                'description' => null,
                'address' => null,
                'google_map' => null,
                'video_url' => null,
                'featured_image' => 'assets/images/properties/E6Kib6NfNQPYrrgLAxXW9RuuVMdhbr14Omgf0vtb.webp',
                'file_attachment' => null,
                'status' => 'active',
                'for_rent' => null,
                'for_sale' => null,
                'hot_offer' => null,
                'sale' => null,
                'sold' => null,
                'created_at' => Carbon::parse('2025-06-12 23:56:46'),
                'updated_at' => Carbon::parse('2025-06-14 11:35:06'),
            ],
            [
                'id' => 5,
                'project_id' => 1,
                'property_name' => 'ONE BHK APARTMENT',
                'property_id' => null,
                'price' => null,
                'before_price_label' => null,
                'after_price_label' => null,
                'price_unit' => null,
                'price_on_call' => 'no',
                'size' => null,
                'land' => null,
                'room' => null,
                'bedroom' => null,
                'bathroom' => null,
                'garages' => null,
                'garages_size' => null,
                'year_built' => null,
                'city_id' => null,
                'state_id' => null,
                'country_id' => null,
                'description' => null,
                'address' => null,
                'google_map' => null,
                'video_url' => null,
                'featured_image' => 'assets/images/properties/yfj98aIEjkL95UQgs6gCGM0YRDJf2dJxBHdzI9B3.webp',
                'file_attachment' => null,
                'status' => 'active',
                'for_rent' => null,
                'for_sale' => null,
                'hot_offer' => null,
                'sale' => null,
                'sold' => null,
                'created_at' => Carbon::parse('2025-06-14 12:21:42'),
                'updated_at' => Carbon::parse('2025-07-06 05:56:51'),
            ],
        ];

        foreach ($properties as $property) {
            Properties::create($property);
        }
    }
}
